=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/demoapp/editors/editor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="editor" type="editorType"/>
  <xs:complexType name="styleType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="groupType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="labelType" name="label"/>
      <xs:element type="textType" name="text"/>
      <xs:element type="plComboType" name="plCombo"/>
      <xs:element type="dateType" name="date"/>
    </xs:choice>
    <xs:attribute type="xs:string" name="title"/>
    <xs:attribute type="xs:string" name="layout"/>
    <xs:attribute type="xs:string" name="cols"/>
    <xs:attribute type="xs:string" name="template"/>
    <xs:attribute type="xs:string" name="colWidth"/>
  </xs:complexType>
  <xs:complexType name="templatesType">
    <xs:sequence>
      <xs:element type="styleType" name="style" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dateType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="property" use="optional"/>
        <xs:attribute type="xs:string" name="mode" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="plComboType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="property" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="labelType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="property" use="optional"/>
        <xs:attribute type="xs:string" name="mode" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="layoutType">
    <xs:sequence>
      <xs:element type="tabType" name="tab">
        <xs:annotation>
          <xs:documentation>The root node of an editor is always a tab...</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="textType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="property" use="optional"/>
        <xs:attribute type="xs:string" name="template" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="tabType">
    <xs:sequence>
      <xs:element type="compositeType" name="composite"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="title"/>
  </xs:complexType>
  <xs:complexType name="editorType">
    <xs:sequence>
      <xs:element type="xs:string" name="id"/>
      <xs:element type="xs:string" name="entity"/>
      <xs:element type="templatesType" name="templates"/>
      <xs:element type="layoutType" name="layout">
        <xs:annotation>
          <xs:documentation>The layout</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="compositeType">
    <xs:sequence>
      <xs:element type="groupType" name="group"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="layout"/>
    <xs:attribute type="xs:string" name="cols"/>
    <xs:attribute type="xs:string" name="style"/>
  </xs:complexType>
</xs:schema>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/crm/editors/SupportCase-default.editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns="http://www.xwic.de" 
		xsi:schemaLocation="http://www.xwic.de editor.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <id>default</id>
    <entity>de.xwic.sandbox.crm.entities.ISupportCase</entity>
    <script><![CDATA[
		
	]]></script>
	
	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="General" layout="grid" cols="2" template="form" colWidth="150;-1">
					
					<label property="caseNumber"/>
					<text property = "caseNumber" template="field"/>

					<label property="shortDescription"/>
					<text property = "shortDescription" template="field"/>

					<label property="customer"/>
					<entity property="customer" template="field"/>

					<label property="reportedBy"/>
					<entity property="reportedBy" template="field"/>

					<label property="description"/>
					<text property = "description" template="field"/>

					<label property="severity"/>
					<plCombo property="severity" template="field"/>


				</group>

 			</composite>
		</tab>

	<!-- Place sub-tabs here -
        <subTabs>
            <subTab title="Title">
                <listView type="entity-class" filterOn="property" listProfile="default"/>
            </subTab>
        </subTabs>
    -->
    </layout>

</editor>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/demoapp/editors/campaign-participant-editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns="http://www.xwic.de" 
		xsi:schemaLocation="http://www.xwic.de editor.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<id>default</id>
	<entity>de.xwic.sandbox.demoapp.model.entities.ICampaignParticipant</entity>

	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="General" layout="grid" cols="2" template="form" colWidth="150;-1">
					<label property="campaign"/>
					<entity property="campaign"/>
					<label property="company"/>
					<entity property="company"/>
					<label property="contact"/>
					<entity property="contact"/>
				</group>
 			</composite>
		</tab>
	</layout>

</editor>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/demoapp/editors/contact-editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xsi:noNamespaceSchemaLocation="editor.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>default</id>
	<entity>de.xwic.sandbox.demoapp.model.entities.IContact</entity>
	<script><![CDATA[
		
		function isUSA() {
			if (entity.getCountry() != null) {
				//log.info("Country is " + entity.getCountry().getKey());
				return entity.getCountry().getKey() == 'usa';
			}
			return false; 
		}
		
	]]></script>
	
	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="Basics" layout="grid" cols="2" template="form" colWidth="150;-1">
					
					<label property="title"/>
					<plRadio property="title" cols="5"/> 
					<!-- <plCombo property="title"/> -->
					
					<label property="firstName"/>
					<text property = "firstName" template="field"/>
					
					<label property="middleName" hideWhen="entity.getTitle() == null"/>
					<text property = "middleName" template="field" hideWhen="entity.getTitle() == null"/>
	
					<label property="lastName"/>
					<text property = "lastName" template="field"/>
					
				</group>

				<group title="Address" layout="grid" cols="2" template="form" colWidth="150;-1">
					<label property="address1"/>
					<text property = "address1" template="field"/>

					<label property="address2"/>
					<text property = "address2" template="field"/>
					
					<label property="zip"/>
					<text property = "zip" template="field"/>
	
					<label property="city"/>
					<text property = "city" template="field"/>

					<label property="country"/>
					<plCombo property = "country" template="field"/>
					
					<label property="state" hideWhen="!isUSA()"/>
					<text property = "state" template="field" hideWhen="!isUSA()"/>
					 
				</group>
 			</composite>
		</tab>
		<tab title="More">
			<composite layout="grid" cols="2" style="padding: 2">

				<group title="Contact" layout="grid" cols="2" template="form" colWidth="150;-1;">
					<label property="phone1"/>
					<text property = "phone1" template="field"/>
					
					<label property="phone2"/>
					<text property = "phone2" template="field"/>
	
					<label property="fax"/>
					<text property = "fax" template="field"/>

					<label property="email1"/>
					<text property = "email1" template="field"/>

					<label property="email2"/> 
					<text property = "email2" template="field"/>

					<label property="webSite"/>
					<text property = "webSite" template="field"/>

					<label property="displayName"/>
					<yesNoRadio property="displayName" template="field"/>


				</group>

				<group title="Notes" layout="grid" cols="1" template="form">
					<text property="notes" multiline="true" style="width: 415; height: 177"/>
				</group>				
			</composite>
		</tab>
	</layout>

</editor>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/crm/editors/Customer-default.editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns="http://www.xwic.de" 
		xsi:schemaLocation="http://www.xwic.de editor.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <id>default</id>
    <entity>de.xwic.sandbox.crm.entities.ICustomer</entity>
    <script><![CDATA[
		
	]]></script>
	
	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="General" layout="grid" cols="2" template="form" colWidth="150;-1">
					
					<label property="name"/>
					<text property = "name" template="field"/>

					<label property="address1"/>
					<text property = "address1" template="field"/>

					<label property="address2"/>
					<text property = "address2" template="field"/>

					<label property="zipCode"/>
					<text property = "zipCode" template="field"/>

					<label property="city"/>
					<text property = "city" template="field"/>

					<label property="country"/>
					<text property = "country" template="field"/>

					<label property="webSite"/>
					<text property = "webSite" template="field"/>


				</group>

 			</composite>
		</tab>

        <subTabs>
            <subTab title="Contacts">
                <listView type="de.xwic.sandbox.crm.entities.IContact" filterOn="customer" listProfile="default"/>
            </subTab>
            <subTab title="Products">
                <listView type="de.xwic.sandbox.crm.entities.IInstallBase" filterOn="customer" listProfile="default"/>
            </subTab>
        </subTabs>

    </layout>

</editor>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/crm/editors/Contact-default.editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns="http://www.xwic.de" 
		xsi:schemaLocation="http://www.xwic.de editor.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <id>default</id>
    <entity>de.xwic.sandbox.crm.entities.IContact</entity>
    <script><![CDATA[
		
	]]></script>
	
	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="General" layout="grid" cols="2" template="form" colWidth="150;-1">
					
					<label property="customer"/>
					<entity property="customer" template="field"/>

					<label property="name"/>
					<text property = "name" template="field"/>

					<label property="email"/>
					<text property = "email" template="field"/>

					<label property="phone"/>
					<text property = "phone" template="field"/>

					<label property="mobile"/>
					<text property = "mobile" template="field"/>

					<label property="fax"/>
					<text property = "fax" template="field"/>

					<label property="role"/>
					<plCombo property="role" template="field"/>


				</group>

 			</composite>
		</tab>

	<!-- Place sub-tabs here -
        <subTabs>
            <subTab title="Title">
                <listView type="entity-class" filterOn="property" listProfile="default"/>
            </subTab>
        </subTabs>
    -->
    </layout>

</editor>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/crm/editors/InstallBase-default.editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xmlns="http://www.xwic.de" 
		xsi:schemaLocation="http://www.xwic.de editor.xsd"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <id>default</id>
    <entity>de.xwic.sandbox.crm.entities.IInstallBase</entity>
    <script><![CDATA[
		
	]]></script>
	
	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="General" layout="grid" cols="2" template="form" colWidth="150;-1">
					
					<label property="customer"/>
					<entity property="customer" template="field"/>

					<label property="product"/>
					<entity property="product" template="field"/>

					<label property="serialNr"/>
					<text property = "serialNr" template="field"/>

					<label property="purchaseDate"/>
					<date property="purchaseDate" template="field"/>


				</group>

 			</composite>
		</tab>

	<!-- Place sub-tabs here -
        <subTabs>
            <subTab title="Title">
                <listView type="entity-class" filterOn="property" listProfile="default"/>
            </subTab>
        </subTabs>
    -->
    </layout>

</editor>

=== xwic/sandbox/de.xwic.sandbox.server/web_root/config/demoapp/editors/campaign-editor.xml
<?xml version="1.0" encoding="UTF-8"?>
<editor xsi:noNamespaceSchemaLocation="editor.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>default</id>
	<entity>de.xwic.sandbox.demoapp.model.entities.ICampaign</entity>

	<templates>
		<style id="form">
			padding: 5;
		</style>
		<style id="field">
			width: 350;
		</style>
	</templates>
	
	<!-- The layout-->
	<layout>
		<!-- The root node of an editor is always a tab... -->
		<tab title="General">
			<composite layout="grid" cols="2" style="padding: 2">
				<group title="General" layout="grid" cols="2" template="form" colWidth="150;-1">
					<label property="name"/>
					<text property = "name" template="field"/>

					<label property="type"/>
					<plCombo property="type"/>
				</group>
 			</composite>
		</tab>
	</layout>

</editor>
